In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd "/content/drive/MyDrive/04-novel-stereonet-v04"

/content/drive/MyDrive/04-novel-stereonet-v04


In [3]:
#pip install -r ./req-cluster.txt -
!cat ./req-cluster.txt | xargs -n 1 pip install

ERROR: Could not find a version that satisfies the requirement apex==0.1 (from versions: 0.9.8dev.linux-i686, 0.9.8.dev0, 0.9.8a0.dev0, 0.9.9.dev0, 0.9.10.dev0)
ERROR: No matching distribution found for apex==0.1
     |████████████████████████████████| 107 kB 13.4 MB/s 
     |████████████████████████████████| 14.6 MB 67 kB/s 
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.6.0 requires numpy~=1.19.2, but you have numpy 1.19.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
     |████████████████████████████████| 28.2 MB 73 kB/s 
  Att

In [4]:
!rm -R "/content/drive/MyDrive/04-novel-stereonet-v04/results/"
!sh run.sh


300
[2021-09-04 15:48:28 folder_logs_init.py:178] INFO     ========= The training was started =========
[2021-09-04 15:48:28 folder_logs_init.py:195] INFO     ========= Model cf_fact3d was loaded with number of subspaces is 2 + last Conv1D. BN enabled for the last conv1D only
[2021-09-04 15:48:28 folder_logs_init.py:196] INFO     The used kernels are: [[3, 3, 1], [1, 1, 3], [1, 1, 3]]
[2021-09-04 15:48:28 folder_logs_init.py:206] INFO     BN_1D:1
[2021-09-04 15:48:28 folder_logs_init.py:206] INFO     BN_1D_last:1
[2021-09-04 15:48:28 folder_logs_init.py:206] INFO     BN_2D:0
[2021-09-04 15:48:28 folder_logs_init.py:206] INFO     BN_2D_last:0
[2021-09-04 15:48:28 folder_logs_init.py:206] INFO     abs_thr:3
[2021-09-04 15:48:28 folder_logs_init.py:206] INFO     checkpoint_save_thr:1
[2021-09-04 15:48:28 folder_logs_init.py:206] INFO     chout_costfiltring:32
[2021-09-04 15:48:28 folder_logs_init.py:206] INFO     cuda:True
[2021-09-04 15:48:28 folder_logs_init.py:206] INFO     datapath:./

In [11]:
!rm -R "/content/drive/MyDrive/04-novel-stereonet-v04/results/"
!sh run.sh


300
[2021-09-04 16:45:36 folder_logs_init.py:178] INFO     ========= The training was started =========
[2021-09-04 16:45:36 folder_logs_init.py:195] INFO     ========= Model cf_fact3d was loaded with number of subspaces is 2 + last Conv1D. BN enabled for the last conv1D only
[2021-09-04 16:45:36 folder_logs_init.py:196] INFO     The used kernels are: [[3, 3, 1], [1, 1, 3], [1, 1, 3]]
[2021-09-04 16:45:36 folder_logs_init.py:206] INFO     BN_1D:1
[2021-09-04 16:45:36 folder_logs_init.py:206] INFO     BN_1D_last:1
[2021-09-04 16:45:36 folder_logs_init.py:206] INFO     BN_2D:0
[2021-09-04 16:45:36 folder_logs_init.py:206] INFO     BN_2D_last:0
[2021-09-04 16:45:36 folder_logs_init.py:206] INFO     abs_thr:3
[2021-09-04 16:45:36 folder_logs_init.py:206] INFO     checkpoint_save_thr:1
[2021-09-04 16:45:36 folder_logs_init.py:206] INFO     chout_costfiltring:32
[2021-09-04 16:45:36 folder_logs_init.py:206] INFO     cuda:True
[2021-09-04 16:45:36 folder_logs_init.py:206] INFO     datapath:./

In [ ]:
!sh test.sh

300
[2021-09-04 14:34:13 folder_logs_init.py:178] INFO     ========= The testing was started =========
[2021-09-04 14:34:13 folder_logs_init.py:195] INFO     ========= Model cf_fact3d was loaded with number of subspaces is 2 + last Conv1D. BN enabled for the last conv1D only
[2021-09-04 14:34:13 folder_logs_init.py:196] INFO     The used kernels are: [[3, 3, 1], [1, 1, 3], [1, 1, 3]]
[2021-09-04 14:34:13 folder_logs_init.py:206] INFO     BN_1D:1
[2021-09-04 14:34:13 folder_logs_init.py:206] INFO     BN_1D_last:1
[2021-09-04 14:34:13 folder_logs_init.py:206] INFO     BN_2D:0
[2021-09-04 14:34:13 folder_logs_init.py:206] INFO     BN_2D_last:0
[2021-09-04 14:34:13 folder_logs_init.py:206] INFO     abs_thr:3
[2021-09-04 14:34:13 folder_logs_init.py:206] INFO     checkpoint_save_thr:1
[2021-09-04 14:34:13 folder_logs_init.py:206] INFO     chout_costfiltring:32
[2021-09-04 14:34:13 folder_logs_init.py:206] INFO     cuda:True
[2021-09-04 14:34:13 folder_logs_init.py:206] INFO     datapath:./F

In [ ]:
def disparity_loader(path):
    return readPFM(path)

import re
import numpy as np
import sys


def readPFM(file):
    file = open(file, 'rb')

    color = None
    width = None
    height = None
    scale = None
    endian = None

    header = file.readline().decode('utf-8').rstrip()
    
    if header == 'PF':
        color = True
    elif header == 'Pf':
        color = False
    else:
        raise Exception('Not a PFM file.')
    dim_match = re.match(r'^(\d+)\s(\d+)\s$', file.readline().decode('utf-8'))
    if dim_match:
        width, height = map(int, dim_match.groups())
    else:
        raise Exception('Malformed PFM header.')

    scale = float(file.readline().rstrip())
    if scale < 0:  # little-endian
        endian = '<'
        scale = -scale
    else:
        endian = '>'  # big-endian

    data = np.fromfile(file, endian + 'f')
    shape = (height, width, 3) if color else (height, width)

    data = np.reshape(data, shape)
    data = np.flipud(data)
    return data, scale


In [ ]:
d, s = readPFM("/content/drive/MyDrive/04-novel-stereonet-v04/FlyingThings3D/val/disparity/left/0000000.pfm")
d = -1.0 * np.ascontiguousarray(d, dtype=np.float32)
d

array([[ 1.375  ,  1.375  ,  1.375  , ...,  1.53125,  1.53125,  1.53125],
       [ 1.375  ,  1.375  ,  1.375  , ...,  1.5    ,  1.53125,  1.53125],
       [ 1.375  ,  1.375  ,  1.375  , ...,  1.5    ,  1.5    ,  1.53125],
       ...,
       [60.6875 , 60.625  , 60.5625 , ..., 23.34375, 23.375  , 23.375  ],
       [60.65625, 60.5625 , 60.5    , ..., 23.34375, 23.375  , 23.375  ],
       [60.5625 , 60.25   , 59.90625, ..., 23.34375, 23.375  , 23.375  ]],
      dtype=float32)

In [ ]:
import torch
disp = torch.from_numpy(d)
mask = disp > 0
mask

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        ...,
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])

In [ ]:
import torch
count = len(torch.nonzero(mask,as_tuple=False))
count

518400

In [ ]:
from __future__ import print_function
import argparse
import os
import torch
import torch.nn as nn
import torch.nn.parallel
from torch.optim import lr_scheduler
import torch.optim as optim 
import torch.utils.data
import torchvision
from os.path import join, split, isdir, isfile, splitext, split, abspath, dirname
from torch.autograd import Variable
import torch.nn.functional as F
import numpy as np
import time
import cv2 as cv
disp_save = d * 256.0
disp_save_16bits = np.array(disp_save, dtype=np.uint16)
#concat_output.append(disp_save_16bits)

image_name_to_save = "test2.png"
cv.imwrite(image_name_to_save, disp_save_16bits)

True

In [ ]:
import torch
a = torch.randint(0,10,(2,5,6))
a

tensor([[[8, 4, 7, 0, 8, 6],
         [2, 0, 2, 5, 8, 7],
         [1, 7, 9, 1, 0, 5],
         [4, 2, 8, 0, 5, 7],
         [3, 0, 7, 2, 8, 6]],

        [[1, 0, 3, 4, 3, 5],
         [4, 4, 7, 0, 6, 1],
         [5, 3, 2, 8, 4, 1],
         [2, 4, 8, 7, 5, 1],
         [6, 2, 8, 3, 1, 3]]])

In [ ]:
a[a>0]=255
a

tensor([[[255, 255, 255,   0, 255, 255],
         [255,   0, 255, 255, 255, 255],
         [255, 255, 255, 255,   0, 255],
         [255, 255, 255,   0, 255, 255],
         [255,   0, 255, 255, 255, 255]],

        [[255,   0, 255, 255, 255, 255],
         [255, 255, 255,   0, 255, 255],
         [255, 255, 255, 255, 255, 255],
         [255, 255, 255, 255, 255, 255],
         [255, 255, 255, 255, 255, 255]]])

In [ ]:
a

tensor([5, 6, 9, 3, 2, 8, 2, 3, 6, 2, 7, 7, 8, 2, 6, 4, 2, 1, 6, 1, 8, 8, 6, 7,
        6, 7, 6, 4, 4, 1, 5, 1, 4, 8, 6, 5, 8, 8, 1, 1, 1, 5, 5, 8, 6, 3, 2, 4,
        1, 6, 4, 1, 7, 7, 6, 7, 1])